language: node_js
node_js:
- node
warnings_are_errors: false
install:
- npm install
script:
- npm run build --prod
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: BCao97bK9eCY5JFZt1Axp3nDqME9D1qMADb//gX1m/MePy8aBOy7F7PXvKSFgylKQNIGisC8rxVOwpI9ZdPcf3BVCpEfx8DMt4RsBKMNKm9/i2PHveTXf+ys1HqLqvq2n9Zx6ez9me3yjdoJ0sr6smew50KbdLo8QMEqyfFpkTTgjCwvJOaWf05Lth8dTuKnKJHgGSc3BQt4pIvc98TKH+MmYqkB/SiV8/niNEwGRMDckoRQXK/B+vhS1Gtcm6xuW17M1ifc65nSpYdYgyiFxlFkdmjDYdD3DRfuES3NlTYb+7eSQQxW19Fyts3B6LOEEP0POxSWG+xYjsPhN1nwAeMFNAhz1uPWu/PptQLSl1EYp0pm51K/q6PcwFBiSSxzPdgOOOu3nK/X1mHBgtTIC5KWDsJ/wBISPlCXRuf81ncT4Som5yU7ge0dRMUD3bb3KlBs92XY4AJ/nR++AkVFdSIbZa/FForv3bfRcZckyfs18dwcnfE6DrukPMkeEH55BQOEWYVaUFtDO48zPZ+viyxU1IbpnpMCO/DZmBnAGMFv3MToutoOhwbtq3yf2WtoPPRwFTv7S8G78fTWefd6eFdMCH+lgJMG4EpTX/XI/xx4tMGQNyhFuDNKar1QptQHJib1KmuMo+kiOrzCXW5n/fNMe3Ib8cnp2AHUA+hv91U=
branches:
  only:
  - master